name: "Run TODO to Issue"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ["playground"]
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
